config/routes.rb
Rails.application.routes.draw do

  #Post
  resources :posts do 
    member do 
      patch :create_element
      patch :delete_element
    end
  end
  patch "open_new_post" => "posts#open_new"

  #Repository
  patch "show_repository" => "contacts#show_sn"
  patch "show_contacts" => "contacts#show"
  patch "show_groups" => "groups#show"
  patch "show_companies" => "companies#show"

  #Project
  resources :projects do 
    member do
      # For Params
      patch :open_params
      patch :quit
      patch :expel
      patch :upd_role
      patch :fav
      patch :mute
      patch :unfav
      patch :unmute
      # For each features
      get :taskboard
      get :calendar
      get :cloud
    end
  end

  resources :email_projects
  patch "open_new_project" => "projects#open_new"

  #User
  devise_for :users
  resources :user_infos

  #Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # ROOT
  authenticated :user do
    root to: "pages#home", as: :authenticated_root
  end
  unauthenticated do
    root 'pages#landing'
  end

  #Test Page
  get "test" => "pages#test"

end

app/views/pages/nav/_navin.html.erb
<div class="navbar">
  <div class="navbar_left">
    <div class="navbtn_r">
      <a href="/" class='logo_btn'>
        <%= image_tag "logo1.png", class: "logo"%>
      </a>
    </div>
  </div>
  <div class="navbar_center">
    <a href="#1" class='navbtn nb_link tooltipped' id="nb_link1" data-position="bottom" data-tooltip="Actualités">
      <%= image_tag "home_w.png", class: "nb_picto"%>
    </a>
    <a href="#2" class='navbtn_r nb_link tooltipped' id="nb_link2" data-position="bottom" data-tooltip="Tâches">
      <%= image_tag "task_w.png", class: "nb_picto"%>
    </a>
    <a href="#3" class='navbtn_r nb_link tooltipped' id="nb_link3" data-position="bottom" data-tooltip="Evènements">
      <%= image_tag "calendar_w.png", class: "nb_picto"%>
    </a>
    <a href="#4" class='navbtn_r nb_link tooltipped' id="nb_link4" data-position="bottom" data-tooltip="Fichiers">
      <%= image_tag "cloud_w.png", class: "nb_picto2"%>
    </a>
  </div>
  <div class="navbar_right">
     <a href="#4" class='navbtn_l nb_link' style='padding-right: 10px; padding-left: 10px;'>
      <%= image_tag "mail_w.png", class: "nb_picto2"%>
    </a>
    <div class="navbtn_l nb_link" id="btn_dropdown">
      <%= image_tag "user1_w.png", class: "nb_picto"%>
    </div>
  </div>
</div>
<div class="nb_dropdown undisplay">
  <%- if current_user.admin? %>
  <a href="/admin" class="nb_dropdown_item">
    <%= image_tag "admin.png", class: 'nb_dropdown_icon' %>
    <div class="nb_dropdown_title">
      Admin
    </div>
  </a>
  <% end %>
  <a href="#" class="nb_dropdown_item">
    <%= image_tag "user1.png", class: 'nb_dropdown_icon' %>
    <div class="nb_dropdown_title">
      Profil
    </div>
  </a>
  <a href="#" class="nb_dropdown_item">
    <%= image_tag "building.png", class: 'nb_dropdown_icon' %>
    <div class="nb_dropdown_title">
      Entreprise
    </div>
  </a>
  <a href="/show_repository" data-method='patch' data-remote="true" class="nb_dropdown_item">
    <%= image_tag "adressbook.png", class: 'nb_dropdown_icon' %>
    <div class="nb_dropdown_title">
      Carnet d'adresse
    </div>
  </a>
  <a href="#" class="nb_dropdown_item">
    <%= image_tag "cog2.png", class: 'nb_dropdown_icon' %>
    <div class="nb_dropdown_title">
      Paramètres
    </div>
  </a>
  <a href="/users/sign_out" data-method="delete" data-confirm="Vous nous quittez déjà ?" class="nb_dropdown_item">
    <%= image_tag "power.png", class: 'nb_dropdown_icon' %>
    <div class="nb_dropdown_title">
      Deconnection
    </div>
  </a>
</div>
<script>
  
  $(document).ready(function () {
    $('.tooltipped').tooltip();
    // Open dropdown (btn)
    $('#btn_dropdown').on('click', function (event) {
      $('.nb_dropdown').slideToggle();
    });
    // href & highlight div
    var pathname = window.location.pathname;
    var project = pathname.split("/")[2]
    if(pathname == '/'){
       $('#nb_link1').addClass('active')
       $('#nb_link2').attr('href', '/tasks')
       $('#nb_link3').attr('href', '/events')
       $('#nb_link4').attr('href', '/clouds')
    } else if(pathname == '/projects/'+ project ){
       $('#nb_link1').addClass('active')
       $('#nb_link2').attr('href', '/projects/'+project+'/taskboard')
       $('#nb_link3').attr('href', '/projects/'+project+'/calendar')
       $('#nb_link4').attr('href', '/projects/'+project+'/cloud')
    } else if(pathname == '/tasks'){
      $('#nb_link1').attr('href', '/')
      $('#nb_link2').addClass('active')
      $('#nb_link3').attr('href', '/events')
      $('#nb_link4').attr('href', '/clouds')
    } else if(pathname == '/projects/'+ project +'/taskboard'){
      $('#nb_link1').attr('href', '/projects/'+project)
      $('#nb_link2').addClass('active')
      $('#nb_link3').attr('href', '/projects/'+project+'/calendar')
      $('#nb_link4').attr('href', '/projects/'+project+'/cloud')
    } else if(pathname == '/events'){
      $('#nb_link1').attr('href', '/')
      $('#nb_link2').attr('href', '/tasks')
      $('#nb_link3').addClass('active')
      $('#nb_link4').attr('href', '/clouds')
    } else if(pathname == '/projects/'+project+'/calendar'){
      $('#nb_link1').attr('href', '/projects/'+project)
      $('#nb_link2').attr('href', '/projects/'+project+'/taskboard')
      $('#nb_link3').addClass('active')
      $('#nb_link4').attr('href', '/projects/'+project+'/cloud')
    }else if(pathname == '/clouds'){
      $('#nb_link1').attr('href', '/')
      $('#nb_link2').attr('href', '/tasks')
      $('#nb_link3').attr('href', '/events')
      $('#nb_link4').addClass('active')
    } else if(pathname == '/projects/'+project+'/cloud'){
      $('#nb_link1').attr('href', '/projects/'+project)
      $('#nb_link2').attr('href', '/projects/'+project+'/taskboard')
      $('#nb_link3').attr('href', '/projects/'+project+'/calendar')
      $('#nb_link4').addClass('active')
    } else {
      $('#nb_link1').attr('href', '/')
      $('#nb_link2').attr('href', '/tasks')
      $('#nb_link3').attr('href', '/events')
      $('#nb_link4').attr('href', '/clouds')
    }
  });
  // If click out close dropdown
  $(document).mouseup(function(e) {
    var container = $('.nb_dropdown, #btn_dropdown')
    if (!container.is(e.target) && container.has(e.target).length === 0) { $('.nb_dropdown').slideUp(); }
  });
</script>

app/views/pages/nav/_navout.html.erb
<div class="navbar" style="background: #FAFAFA; opacity: 0.9;">
  <div class="navbar_left">
    <a href="/" class='logo_btn'>
      <%= image_tag "logo6.png", class: "logo2"%>
    </a>   
  </div>
  <div class="space"></div>
  <a class="waves-effect waves-light btn" style="width: 250px; margin: 12px;" id="modal_signin_btn"><i class="material-icons left">person</i>Connection</a>
</div>
<!-- Modal Sign In -->
<div id="modal_signin" class="modal" style="max-height: 100%; width: 400px;">
  <div class="modal-header">
    <h4>Connection</h4>
  </div>
  <div class="modal-content" style="text-align: center;">
    <div class="row" style=" padding: 0 20px; margin:0;">
      <%= form_for(:user, :url => session_path(:user)) do |f| %>
        <div class="input-field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
        <div class="input-field">
          <%= f.label :password, 'Mot de passe' %>
          <%= f.password_field :password %>
        </div>
        <div style="padding: 20px;">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me, "Se souvenir de moi ?" %>
        </div>
        <%= f.submit "c'est parti !", class: "btn" %>
        <br>
        <br>
        <%= link_to "Mot de passe oublié ?", new_password_path(:user) %>
      <% end %>
    </div>
  </div>

  <div class="modal-footer" style="text-align:left; display:flex; border-top: solid 1px #ddd;">
    <a class="btn btn-flat modal-close"  style="padding-top: 2px;">Annuler</a>
    <div class='space'></div>
    <a class="btn blue lighten-1" style="min-width: 200px; padding-top: 2px;" id="modal_signup_btn">Pas inscrit ?</a>
  </div>
</div>
<!-- Modal Sign Up -->
<div id="modal_signup" class="modal" style="max-height: 100%; width: 400px;">
  <div class="modal-header">
    <h4>Inscription</h4>
  </div>
  <div class="modal-content" style="text-align: center;">
    <div class="row" style=" padding: 0 20px; margin:0;">
      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <div class="input-field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
        <div class="input-field">
          <%= f.label :password, 'Mot de passe' %>
          <%= f.password_field :password, autocomplete: "off" %>
        </div>
        <div class="input-field">
          <%= f.label :password, 'Confirmation mot de passe' %>
          <%= f.password_field :password, autocomplete: "off" %>
        </div>
        <div style="display: flex; width: max-content; margin: auto;">
          <p><input type="checkbox" id="myCheckbox1"/><label for="myCheckbox1"></label></p>
          <p>J'accepte les <a href="">conditions générales d'utilisation</a></p>
        </div>
        <%= f.submit "Inscription", class: "btn" %>
        <br>
        <br>
        <%= link_to "Vous n'avez pas recu le mail de confirmation ?", new_password_path(:user) %>
      <% end %>
    </div>
  </div>
  <div class="modal-footer" style="text-align:left; display:flex; border-top: solid 1px #ddd;">
    <a class="btn btn-flat modal-close"  style="padding-top: 2px;">Annuler</a>
    <div class='space'></div>
    <a class="btn blue lighten-1"  id="modal_signin_btn2" style="min-width: 190px; padding-top: 2px;">Déjà inscrit ?</a>
  </div>
</div>
<script>
  $(document).ready(function () {
    $('.modal').modal();
    $('#modal_signin_btn, #modal_signin_btn2').on('click', function (event) {
      $('#modal_signup').modal('close');
      $('#modal_signin').modal('open');
    });
    $('#modal_signup_btn').on('click', function (event) {
      $('#modal_signin').modal('close');
      $('#modal_signup').modal('open');
    });
  });
</script>

app/views/pages/nav/_sidenav.html.erb
<div class="sidenav">
  <div class="sn_body">
    <!-- General item -->
    <div class="sn_item" id='sn_item_general'>
      <a class="sn_item_body" id="sn_item_body_general" href="#">
        <div class="sn_item_title">
          <div class="sn_item_title_picto">
            <%= image_tag "home.png", class: "sn_picto"%>
          </div>
          <div class="sn_item_title_name" style="padding-top: 2px;">
            Général
          </div>          
        </div>
      </a>
    </div>
    <!-- /General item -->
    <div class="projects">
      <% current_user.projects_notified.each do |user_project| %>
        <%= render 'projects/project', project: user_project.project, user: user_project %>
      <% end %>
      <% current_user.projects_not_notified.each do |user_project| %>
        <%= render 'projects/project', project: user_project.project, user: user_project %>
      <% end %>
      <div class="new_project_zone">
      </div>
      <% current_user.projects_mute.each do |user_project| %>
        <%= render 'projects/project', project: user_project.project, user: user_project %>
      <% end %>
    </div>

  </div>
  <a href="/open_new_project" data-method='patch' data-remote="true" class="sn_footer">
    Créer Projet
  </a>
</div>
<script>
  $(document).ready(function () {
    var pathname = window.location.pathname
    var project = pathname.split("/")[2]
    // Active links General
    if(pathname == '/' || pathname == '/tasks' || pathname == '/events' || pathname == '/clouds' ) {
      $('#sn_item_general').addClass('active');
    }
    // href route
    if(pathname == '/' || pathname == '/projects/'+project){
      $('#sn_item_body_general').attr('href', '/');
    }
    else if(pathname == '/tasks' || pathname == '/projects/'+project+'/taskboard'){
      $('#sn_item_body_general').attr('href', '/tasks');
    }
    else if(pathname == '/events' || pathname == '/projects/'+project+'/calendar'){
      $('#sn_item_body_general').attr('href', '/events');
    }
    else if(pathname == '/clouds' || pathname == '/projects/'+project+'/cloud'){
      $('#sn_item_body_general').attr('href', '/clouds');
    }
  });
</script>